apiVersion: apps/v1
kind: Deployment
metadata:
    name: mastree-sso-deploy
spec:
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
    selector:
        matchLabels:
            app: mastree-sso
            tier: web
    template:
        metadata:
            labels:
                app: mastree-sso
                tier: web
        spec:
            containers:
                - name: mastree-sso
                  image: gcr.io/principal-yen-260608/aerobase/aerobase:1.0.0
                  ports:
                      - containerPort: 80
                        protocol: TCP
                        name: http
                  imagePullPolicy: Always
                  readinessProbe:
                      httpGet:
                          path: /
                          port: 80
                      initialDelaySeconds: 5
                      periodSeconds: 5
                      successThreshold: 2
                      failureThreshold: 2
                      timeoutSeconds: 2
