apiVersion: v1
kind: Service
metadata:
  name: mastree-sso-service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  namespace: default
  labels:
    app: mastree-sso
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app : mastree-sso
    tier: web
  type: LoadBalancer

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mastree-sso-ingress
  annotations:
    kubernetes.io/ingress.allow-http: "true"
  labels:
    app: mastree-sso
spec:
  backend:
    serviceName: mastree-sso-service
    servicePort: 80
    